import moment from 'moment';
class Product {
constructor(
            productId,
            internalName,
            brandName,
            productName,
            comments,
            releaseDate,
            salesDiscontinuationDate,
            weightUomId,
            productWeight
           ) {
  
            this.isCreate= "true",
            this.productId= productId,
            this.productTypeId= "FINISHED_GOOD",
            this.internalName= internalName,
            this.brandName= brandName,
            this.productName= productName,
            this.comments= comments,
            this.isVirtual= "N",
            this.isVariant= "N",
            this.virtualVariantMethodEnum= "",
            this.primaryProductCategoryId= "",
            this.introductionDate_i18n= "",
            this.introductionDate= "",
            this.releaseDate_i18n= "",
            this.releaseDate= moment(releaseDate).format('YYYY-MM-DD').toString(),
            this.salesDiscontinuationDate_i18n= "",
            this.salesDiscontinuationDate= moment(salesDiscontinuationDate).format('YYYY-MM-DD').toString(),
            this.supportDiscontinuationDate_i18n= "",
            this.supportDiscontinuationDate= "",
            this.salesDiscWhenNotAvail= "",
            this.requirementMethodEnumId= "",
            this.inventoryItemTypeId= "NON_SERIAL_INV_ITEM",
            this.requireInventory= "",
            this.inventoryMessage= "",
            this.lotIdFilledIn= "Allowed",
            this.ratingTypeEnum= "",
            this.productRating= "",
            this.requireAmount= "",
            this.amountUomTypeId= "",
            this.productHeight= "",
            this.heightUomId= "",
            this.shippingHeight= "",
            this.productWidth= "",
            this.widthUomId= "",
            this.shippingWidth= "",
            this.productDepth= "",
            this.depthUomId= "",
            this.shippingDepth= "",
            this.productDiameter= "",
            this.diameterUomId= "",
            this.productWeight= productWeight,
            this.weightUomId= "",
            this.shippingWeight= "",
            this.quantityIncluded= "",
            this.quantityUomId= "",
            this.piecesIncluded= "",
            this.inShippingBox= "N",
            this.defaultShipmentBoxTypeId= "",
            this.chargeShipping= "",
            this.orderDecimalQuantity= "",
            this.returnable= "",
            this.includeInPromotions= "",
            this.taxable= ""
}
}
module.exports = Product
